# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Render < Formula
  desc "Rendering files using Sigil templating."
  homepage "https://github.com/winebarrel/render"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/render/releases/download/v1.0.1/render_1.0.1_darwin_amd64.tar.gz"
      sha256 "8c0f277093954bef46c75d4811612fdbedf311d2212911312ef55bee2fad97ae"

      def install
        bin.install 'render'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/render/releases/download/v1.0.1/render_1.0.1_darwin_arm64.tar.gz"
      sha256 "eef04f2ca3736fd3c46959d075ffebc7efc1b19c50e5b2f508563acc6dd65319"

      def install
        bin.install 'render'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/render/releases/download/v1.0.1/render_1.0.1_linux_amd64.tar.gz"
      sha256 "6077b45b2fffa769188810ce98cd867421001889a1f2bd1212d1a9975803ca5d"

      def install
        bin.install 'render'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/render/releases/download/v1.0.1/render_1.0.1_linux_arm64.tar.gz"
      sha256 "21369c993df9274e3dc6dbf767b3739d70578f8e7bec54a4a5bfeed283a05207"

      def install
        bin.install 'render'
      end
    end
  end
end
