# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Render < Formula
  desc "Rendering files using Sigil templating."
  homepage "https://github.com/winebarrel/render"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/render/releases/download/v1.0.0/render_1.0.0_darwin_arm64.tar.gz"
      sha256 "014145b890d768245767f0b5b51f7690dcc292cdd9fb444158aa0b0a67a581d7"

      def install
        bin.install 'render'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/render/releases/download/v1.0.0/render_1.0.0_darwin_amd64.tar.gz"
      sha256 "37c375068c7fa5eb6622c5b55d72a5eca1d0bc053efbca2fc9329f44faa9f4e1"

      def install
        bin.install 'render'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/render/releases/download/v1.0.0/render_1.0.0_linux_arm64.tar.gz"
      sha256 "b985ffc6c485f627112ad36df5edbde38d238dc0ba9f6c99a7e2f07be39e14b5"

      def install
        bin.install 'render'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/render/releases/download/v1.0.0/render_1.0.0_linux_amd64.tar.gz"
      sha256 "87501d3e3bf5aba4221202f49220ed1c6e23373cd4c23760049453f06708f9ea"

      def install
        bin.install 'render'
      end
    end
  end
end
